import {
  LayoutDashboard,
  FileText,
  FolderOpen,
  Users,
  PlusCircle,
  Shield,
  Palette,
  Rss,
  MessageSquare,
  Tag,
  Sparkles,
  AudioLines,
  Brain,
  Type,
  ShieldCheck,
  KeyRound,
  UserCircle,
  SquareStack,
  PieChart,
  Activity,
  MousePointer,
  SplitSquareHorizontal,
  FlaskConical,
  Settings,
  Plug,
  Cloud,
  ListChecks,
  Newspaper,
  Bell,
  User,
  Flame,
  Boxes,
  Lightbulb,
  Telescope,
  Grid3x3,
  Podcast,
  Megaphone,
  BookOpen,
  Calendar,
  Link,
} from "lucide-react";
import type { NavItem } from "./types";

/**
 * English Navigation Configuration
 * Single Source of Truth for all English dashboard navigation items
 */
export const englishNavConfig: NavItem[] = [
  {
    id: "dashboard",
    labelKey: "nav.dashboard",
    labelAr: "نظرة عامة",
    labelEn: "Overview",
    path: "/en/dashboard",
    icon: LayoutDashboard,
    roles: ["admin", "editor", "author", "reviewer", "analyst", "reporter"],
    meta: { exact: true },
  },

  // ===== المحتوى / Content =====
  {
    id: "content",
    labelKey: "nav.content",
    labelAr: "المحتوى",
    labelEn: "Content",
    icon: Newspaper,
    roles: ["admin", "editor", "author", "reviewer"],
    children: [
      {
        id: "articles",
        labelKey: "nav.articles",
        labelAr: "الأخبار والمقالات",
        labelEn: "News & Articles",
        path: "/en/dashboard/articles",
        icon: FileText,
        roles: ["admin", "editor", "author", "reviewer"],
      },
      {
        id: "new_article",
        labelKey: "nav.new_article",
        labelAr: "مقال جديد",
        labelEn: "New Article",
        path: "/en/dashboard/articles/new",
        icon: PlusCircle,
        roles: ["admin", "editor", "author"],
      },
      {
        id: "categories",
        labelKey: "nav.categories",
        labelAr: "التصنيفات",
        labelEn: "Categories",
        path: "/en/dashboard/categories",
        icon: FolderOpen,
        roles: ["admin", "editor"],
      },
      {
        id: "tags",
        labelKey: "nav.tags",
        labelAr: "الوسوم",
        labelEn: "Tags",
        path: "/en/dashboard/tags",
        icon: Tag,
        roles: ["admin", "editor"],
      },
      {
        id: "smart_links",
        labelKey: "nav.smart_links",
        labelAr: "الروابط الذكية",
        labelEn: "Smart Links",
        path: "/en/dashboard/smart-links",
        icon: Link,
        roles: ["admin", "editor"],
      },
      {
        id: "comments",
        labelKey: "nav.comments",
        labelAr: "التعليقات",
        labelEn: "Comments",
        path: "/en/dashboard/comments",
        icon: MessageSquare,
        roles: ["admin", "editor", "reviewer"],
      },
      {
        id: "muqtarib",
        labelKey: "nav.muqtarib",
        labelAr: "مُقترب",
        labelEn: "Muqtarib",
        path: "/en/dashboard/muqtarib",
        icon: Boxes,
        roles: ["admin", "editor"],
      },
      {
        id: "mirqab",
        labelKey: "nav.mirqab",
        labelAr: "المرقاب",
        labelEn: "Mirqab",
        path: "/en/dashboard/mirqab",
        icon: Telescope,
        roles: ["admin", "editor"],
      },
      {
        id: "audio_newsletters",
        labelKey: "nav.audio_newsletters",
        labelAr: "النشرات الصوتية",
        labelEn: "Audio Newsletters",
        path: "/en/dashboard/audio-newsletters",
        icon: Podcast,
        roles: ["admin", "editor"],
      },
      {
        id: "audio_briefs",
        labelKey: "nav.audio_briefs",
        labelAr: "الأخبار الصوتية السريعة",
        labelEn: "Audio Briefs",
        path: "/en/dashboard/audio-briefs",
        icon: AudioLines,
        roles: ["admin", "editor"],
      },
      {
        id: "calendar",
        labelKey: "nav.calendar",
        labelAr: "تقويم سبق",
        labelEn: "Sabq Calendar",
        path: "/en/dashboard/calendar",
        icon: Calendar,
        roles: ["admin", "editor"],
      },
    ],
  },

  // ===== الدردشة / Chat =====
  {
    id: "chat",
    labelKey: "nav.chat",
    labelAr: "المحادثات",
    labelEn: "Chat",
    path: "/en/dashboard/chat",
    icon: MessageSquare,
    roles: ["admin", "editor", "author", "reviewer", "analyst", "reporter"],
  },
  {
    id: "chat_admin",
    labelKey: "nav.chat_admin",
    labelAr: "إدارة الدردشة",
    labelEn: "Chat Admin",
    path: "/en/dashboard/chat-admin",
    icon: Shield,
    roles: ["admin"],
  },

  // ===== الذكاء الاصطناعي / AI =====
  {
    id: "ai",
    labelKey: "nav.ai",
    labelAr: "الذكاء الاصطناعي",
    labelEn: "AI",
    icon: Sparkles,
    roles: ["admin", "editor", "analyst"],
    featureFlags: ["aiDeepAnalysis"],
    children: [
      {
        id: "ai_summaries",
        labelKey: "nav.ai_summaries",
        labelAr: "الملخصات الصوتية",
        labelEn: "Audio Summaries",
        path: "/en/dashboard/ai/summaries",
        icon: AudioLines,
        roles: ["admin", "editor"],
      },
      {
        id: "ai_deep",
        labelKey: "nav.ai_deep_analysis",
        labelAr: "التحليل العميق",
        labelEn: "Deep Analysis",
        path: "/en/dashboard/ai/deep",
        icon: Brain,
        roles: ["admin", "analyst"],
      },
      {
        id: "ai_headlines",
        labelKey: "nav.ai_headlines",
        labelAr: "العناوين الذكية",
        labelEn: "Smart Headlines",
        path: "/en/dashboard/ai/headlines",
        icon: Type,
        roles: ["admin", "editor"],
      },
    ],
  },

  // ===== المستخدمون والأدوار / Users & Roles =====
  {
    id: "users",
    labelKey: "nav.users_and_roles",
    labelAr: "المستخدمون والأدوار",
    labelEn: "Users & Roles",
    icon: Users,
    roles: ["admin"],
    children: [
      {
        id: "users_mgmt",
        labelKey: "nav.users",
        labelAr: "المستخدمون",
        labelEn: "Users",
        path: "/en/dashboard/users",
        icon: UserCircle,
        roles: ["admin"],
      },
      {
        id: "roles",
        labelKey: "nav.roles",
        labelAr: "الأدوار والصلاحيات",
        labelEn: "Roles & Permissions",
        path: "/en/dashboard/roles",
        icon: ShieldCheck,
        roles: ["admin"],
      },
      {
        id: "permissions",
        labelKey: "nav.permissions",
        labelAr: "الصلاحيات",
        labelEn: "Permissions",
        path: "/en/dashboard/permissions",
        icon: KeyRound,
        roles: ["admin"],
      },
    ],
  },

  // ===== المظهر / Appearance =====
  {
    id: "appearance",
    labelKey: "nav.appearance",
    labelAr: "المظهر",
    labelEn: "Appearance",
    icon: Palette,
    roles: ["admin", "editor"],
    featureFlags: ["smartThemes"],
    children: [
      {
        id: "themes",
        labelKey: "nav.themes",
        labelAr: "السمات",
        labelEn: "Themes",
        path: "/en/dashboard/themes",
        icon: Palette,
        roles: ["admin", "editor"],
      },
      {
        id: "templates",
        labelKey: "nav.templates",
        labelAr: "القوالب",
        labelEn: "Templates",
        path: "/en/dashboard/templates",
        icon: SquareStack,
        roles: ["admin", "editor"],
      },
    ],
  },

  // ===== التحليلات / Analytics =====
  {
    id: "analytics",
    labelKey: "nav.analytics",
    labelAr: "التحليلات",
    labelEn: "Analytics",
    icon: PieChart,
    roles: ["admin", "analyst"],
    children: [
      {
        id: "dashboards",
        labelKey: "nav.analytics_dashboards",
        labelAr: "لوحات التحليلات",
        labelEn: "Analytics Dashboards",
        path: "/en/dashboard/analytics",
        icon: Activity,
        roles: ["admin", "analyst"],
      },
      {
        id: "trending",
        labelKey: "nav.trending",
        labelAr: "الرائج",
        labelEn: "Trending",
        path: "/en/dashboard/analytics/trending",
        icon: Flame,
        roles: ["admin", "analyst"],
      },
      {
        id: "behavior",
        labelKey: "nav.user_behavior",
        labelAr: "سلوك المستخدمين",
        labelEn: "User Behavior",
        path: "/en/dashboard/analytics/behavior",
        icon: MousePointer,
        roles: ["admin", "analyst"],
      },
      {
        id: "abTests",
        labelKey: "nav.ab_tests",
        labelAr: "اختبارات A/B",
        labelEn: "A/B Tests",
        path: "/en/dashboard/analytics/ab-tests",
        icon: FlaskConical,
        roles: ["admin", "editor", "analyst"],
      },
      {
        id: "recommendation-analytics",
        labelKey: "nav.recommendation_analytics",
        labelAr: "إحصائيات التوصيات",
        labelEn: "Recommendation Analytics",
        path: "/en/dashboard/analytics/recommendations",
        icon: Lightbulb,
        roles: ["admin", "analyst"],
      },
    ],
  },

  // ===== المحتوى الذكي / Smart Content =====
  {
    id: "smart_content",
    labelKey: "nav.smart_content",
    labelAr: "المحتوى الذكي",
    labelEn: "Smart Content",
    icon: Grid3x3,
    roles: ["admin"],
    children: [
      {
        id: "smart_blocks",
        labelKey: "nav.smart_blocks",
        labelAr: "البلوكات الذكية",
        labelEn: "Smart Blocks",
        path: "/en/dashboard/smart-blocks",
        icon: Grid3x3,
        roles: ["admin"],
      },
      {
        id: "quad_categories_block",
        labelKey: "nav.quad_categories_block",
        labelAr: "بلوك التصنيفات الرباعية",
        labelEn: "Quad Categories Block",
        path: "/en/dashboard/blocks/quad-categories",
        icon: SquareStack,
        roles: ["admin"],
      },
    ],
  },

  // ===== الإعدادات / Settings =====
  {
    id: "settings",
    labelKey: "nav.settings",
    labelAr: "الإعدادات",
    labelEn: "Settings",
    icon: Settings,
    roles: ["admin"],
    children: [
      {
        id: "rss_feeds",
        labelKey: "nav.rss_feeds",
        labelAr: "مصادر RSS",
        labelEn: "RSS Feeds",
        path: "/en/dashboard/rss-feeds",
        icon: Rss,
        roles: ["admin"],
      },
      {
        id: "integrations",
        labelKey: "nav.integrations",
        labelAr: "التكاملات",
        labelEn: "Integrations",
        path: "/en/dashboard/integrations",
        icon: Plug,
        roles: ["admin"],
      },
      {
        id: "storage",
        labelKey: "nav.storage",
        labelAr: "التخزين",
        labelEn: "Storage",
        path: "/en/dashboard/storage",
        icon: Cloud,
        roles: ["admin"],
      },
      {
        id: "audits",
        labelKey: "nav.audit_logs",
        labelAr: "سجلات النشاط",
        labelEn: "Audit Logs",
        path: "/en/dashboard/audit-logs",
        icon: ListChecks,
        roles: ["admin"],
      },
      {
        id: "announcements",
        labelKey: "nav.announcements",
        labelAr: "الإعلانات الداخلية",
        labelEn: "Internal Announcements",
        path: "/en/dashboard/announcements",
        icon: Megaphone,
        roles: ["admin"],
      },
      {
        id: "system_settings",
        labelKey: "nav.system_settings",
        labelAr: "إعدادات النظام",
        labelEn: "System Settings",
        path: "/en/dashboard/system-settings",
        icon: Settings,
        roles: ["admin"],
      },
    ],
  },

  // ===== الملف الشخصي / Profile (Divider before) =====
  {
    id: "profile",
    labelKey: "nav.profile",
    labelAr: "الملف الشخصي",
    labelEn: "Profile",
    path: "/en/dashboard/profile",
    icon: User,
    roles: ["admin", "editor", "author", "reviewer", "analyst"],
    divider: true,
  },

  {
    id: "notifications",
    labelKey: "nav.notifications",
    labelAr: "الإشعارات",
    labelEn: "Notifications",
    path: "/en/dashboard/notifications",
    icon: Bell,
    roles: ["admin", "editor", "author", "reviewer", "analyst"],
  },
];
