import {
  LayoutDashboard,
  FileText,
  FolderOpen,
  Users,
  PlusCircle,
  Shield,
  Palette,
  Rss,
  MessageSquare,
  Tag,
  Sparkles,
  AudioLines,
  Brain,
  Type,
  ShieldCheck,
  KeyRound,
  UserCircle,
  SquareStack,
  PieChart,
  Activity,
  MousePointer,
  SplitSquareHorizontal,
  FlaskConical,
  Settings,
  Plug,
  Cloud,
  ListChecks,
  Newspaper,
  Bell,
  User,
  Flame,
  Boxes,
  Lightbulb,
  Telescope,
  Grid3x3,
  Podcast,
  Megaphone,
  BookOpen,
  Calendar,
} from "lucide-react";
import type { NavItem } from "./types";

/**
 * مصدر الحقيقة الواحد لجميع عناصر القائمة الجانبية
 * Single Source of Truth for all navigation items
 */
export const navConfig: NavItem[] = [
  {
    id: "dashboard",
    labelKey: "nav.dashboard",
    labelAr: "نظرة عامة",
    path: "/dashboard",
    icon: LayoutDashboard,
    roles: ["admin", "editor", "author", "reviewer", "analyst", "reporter"],
    meta: { exact: true },
  },

  // ===== المحتوى / Content =====
  {
    id: "content",
    labelKey: "nav.content",
    labelAr: "المحتوى",
    icon: Newspaper,
    roles: ["admin", "editor", "author", "reviewer"],
    children: [
      {
        id: "articles",
        labelKey: "nav.articles",
        labelAr: "الأخبار والمقالات",
        path: "/dashboard/articles",
        icon: FileText,
        roles: ["admin", "editor", "author", "reviewer"],
      },
      {
        id: "new_article",
        labelKey: "nav.new_article",
        labelAr: "مقال جديد",
        path: "/dashboard/articles/new",
        icon: PlusCircle,
        roles: ["admin", "editor", "author"],
      },
      {
        id: "categories",
        labelKey: "nav.categories",
        labelAr: "التصنيفات",
        path: "/dashboard/categories",
        icon: FolderOpen,
        roles: ["admin", "editor"],
      },
      {
        id: "tags",
        labelKey: "nav.tags",
        labelAr: "الوسوم",
        path: "/dashboard/tags",
        icon: Tag,
        roles: ["admin", "editor"],
      },
      {
        id: "comments",
        labelKey: "nav.comments",
        labelAr: "التعليقات",
        path: "/dashboard/comments",
        icon: MessageSquare,
        roles: ["admin", "editor", "reviewer"],
      },
      {
        id: "muqtarib",
        labelKey: "nav.muqtarib",
        labelAr: "مُقترب",
        path: "/dashboard/muqtarib",
        icon: Boxes,
        roles: ["admin", "editor"],
      },
      {
        id: "mirqab",
        labelKey: "nav.mirqab",
        labelAr: "المرقاب",
        path: "/dashboard/mirqab",
        icon: Telescope,
        roles: ["admin", "editor"],
      },
      {
        id: "audio_newsletters",
        labelKey: "nav.audio_newsletters",
        labelAr: "النشرات الصوتية",
        path: "/dashboard/audio-newsletters",
        icon: Podcast,
        roles: ["admin", "editor"],
      },
      {
        id: "audio_briefs",
        labelKey: "nav.audio_briefs",
        labelAr: "الأخبار الصوتية السريعة",
        path: "/dashboard/audio-briefs",
        icon: AudioLines,
        roles: ["admin", "editor"],
      },
      {
        id: "calendar",
        labelKey: "nav.calendar",
        labelAr: "تقويم سبق",
        path: "/dashboard/calendar",
        icon: Calendar,
        roles: ["admin", "editor"],
      },
    ],
  },

  // ===== الدردشة / Chat =====
  {
    id: "chat",
    labelKey: "nav.chat",
    labelAr: "المحادثات",
    path: "/dashboard/chat",
    icon: MessageSquare,
    roles: ["admin", "editor", "author", "reviewer", "analyst", "reporter"],
  },
  {
    id: "chat_admin",
    labelKey: "nav.chat_admin",
    labelAr: "إدارة الدردشة",
    path: "/dashboard/chat-admin",
    icon: Shield,
    roles: ["admin"],
  },

  // ===== الذكاء الاصطناعي / AI =====
  {
    id: "ai",
    labelKey: "nav.ai",
    labelAr: "الذكاء الاصطناعي",
    icon: Sparkles,
    roles: ["admin", "editor", "analyst"],
    featureFlags: ["aiDeepAnalysis"],
    children: [
      {
        id: "ai_summaries",
        labelKey: "nav.ai_summaries",
        labelAr: "الملخصات الصوتية",
        path: "/dashboard/ai/summaries",
        icon: AudioLines,
        roles: ["admin", "editor"],
      },
      {
        id: "ai_deep",
        labelKey: "nav.ai_deep_analysis",
        labelAr: "التحليل العميق",
        path: "/dashboard/ai/deep",
        icon: Brain,
        roles: ["admin", "analyst"],
      },
      {
        id: "ai_headlines",
        labelKey: "nav.ai_headlines",
        labelAr: "العناوين الذكية",
        path: "/dashboard/ai/headlines",
        icon: Type,
        roles: ["admin", "editor"],
      },
    ],
  },

  // ===== المستخدمون والأدوار / Users & Roles =====
  {
    id: "users",
    labelKey: "nav.users_and_roles",
    labelAr: "المستخدمون والأدوار",
    icon: Users,
    roles: ["admin"],
    children: [
      {
        id: "users_mgmt",
        labelKey: "nav.users",
        labelAr: "المستخدمون",
        path: "/dashboard/users",
        icon: UserCircle,
        roles: ["admin"],
      },
      {
        id: "roles",
        labelKey: "nav.roles",
        labelAr: "الأدوار والصلاحيات",
        path: "/dashboard/roles",
        icon: ShieldCheck,
        roles: ["admin"],
      },
      {
        id: "permissions",
        labelKey: "nav.permissions",
        labelAr: "الصلاحيات",
        path: "/dashboard/permissions",
        icon: KeyRound,
        roles: ["admin"],
      },
    ],
  },

  // ===== المظهر / Appearance =====
  {
    id: "appearance",
    labelKey: "nav.appearance",
    labelAr: "المظهر",
    icon: Palette,
    roles: ["admin", "editor"],
    featureFlags: ["smartThemes"],
    children: [
      {
        id: "themes",
        labelKey: "nav.themes",
        labelAr: "السمات",
        path: "/dashboard/themes",
        icon: Palette,
        roles: ["admin", "editor"],
      },
      {
        id: "templates",
        labelKey: "nav.templates",
        labelAr: "القوالب",
        path: "/dashboard/templates",
        icon: SquareStack,
        roles: ["admin", "editor"],
      },
    ],
  },

  // ===== التحليلات / Analytics =====
  {
    id: "analytics",
    labelKey: "nav.analytics",
    labelAr: "التحليلات",
    icon: PieChart,
    roles: ["admin", "analyst"],
    children: [
      {
        id: "dashboards",
        labelKey: "nav.analytics_dashboards",
        labelAr: "لوحات التحليلات",
        path: "/dashboard/analytics",
        icon: Activity,
        roles: ["admin", "analyst"],
      },
      {
        id: "trending",
        labelKey: "nav.trending",
        labelAr: "الرائج",
        path: "/dashboard/analytics/trending",
        icon: Flame,
        roles: ["admin", "analyst"],
      },
      {
        id: "behavior",
        labelKey: "nav.user_behavior",
        labelAr: "سلوك المستخدمين",
        path: "/dashboard/analytics/behavior",
        icon: MousePointer,
        roles: ["admin", "analyst"],
      },
      {
        id: "abTests",
        labelKey: "nav.ab_tests",
        labelAr: "اختبارات A/B",
        path: "/dashboard/analytics/ab-tests",
        icon: FlaskConical,
        roles: ["admin", "editor", "analyst"],
      },
      {
        id: "recommendation-analytics",
        labelKey: "nav.recommendation_analytics",
        labelAr: "إحصائيات التوصيات",
        path: "/dashboard/analytics/recommendations",
        icon: Lightbulb,
        roles: ["admin", "analyst"],
      },
    ],
  },

  // ===== المحتوى الذكي / Smart Content =====
  {
    id: "smart_content",
    labelKey: "nav.smart_content",
    labelAr: "المحتوى الذكي",
    icon: Grid3x3,
    roles: ["admin"],
    children: [
      {
        id: "smart_blocks",
        labelKey: "nav.smart_blocks",
        labelAr: "البلوكات الذكية",
        path: "/dashboard/smart-blocks",
        icon: Grid3x3,
        roles: ["admin"],
      },
      {
        id: "quad_categories_block",
        labelKey: "nav.quad_categories_block",
        labelAr: "بلوك التصنيفات الرباعية",
        path: "/dashboard/blocks/quad-categories",
        icon: SquareStack,
        roles: ["admin"],
      },
    ],
  },

  // ===== الإعدادات / Settings =====
  {
    id: "settings",
    labelKey: "nav.settings",
    labelAr: "الإعدادات",
    icon: Settings,
    roles: ["admin"],
    children: [
      {
        id: "rss_feeds",
        labelKey: "nav.rss_feeds",
        labelAr: "مصادر RSS",
        path: "/dashboard/rss-feeds",
        icon: Rss,
        roles: ["admin"],
      },
      {
        id: "integrations",
        labelKey: "nav.integrations",
        labelAr: "التكاملات",
        path: "/dashboard/integrations",
        icon: Plug,
        roles: ["admin"],
      },
      {
        id: "storage",
        labelKey: "nav.storage",
        labelAr: "التخزين",
        path: "/dashboard/storage",
        icon: Cloud,
        roles: ["admin"],
      },
      {
        id: "audits",
        labelKey: "nav.audit_logs",
        labelAr: "سجلات النشاط",
        path: "/dashboard/audit-logs",
        icon: ListChecks,
        roles: ["admin"],
      },
      {
        id: "announcements",
        labelKey: "nav.announcements",
        labelAr: "الإعلانات الداخلية",
        path: "/dashboard/announcements",
        icon: Megaphone,
        roles: ["admin"],
      },
      {
        id: "system_settings",
        labelKey: "nav.system_settings",
        labelAr: "إعدادات النظام",
        path: "/dashboard/system-settings",
        icon: Settings,
        roles: ["admin"],
      },
    ],
  },

  // ===== الملف الشخصي / Profile (Divider before) =====
  {
    id: "profile",
    labelKey: "nav.profile",
    labelAr: "الملف الشخصي",
    path: "/dashboard/profile",
    icon: User,
    roles: ["admin", "editor", "author", "reviewer", "analyst"],
    divider: true,
  },

  {
    id: "notifications",
    labelKey: "nav.notifications",
    labelAr: "الإشعارات",
    path: "/dashboard/notifications",
    icon: Bell,
    roles: ["admin", "editor", "author", "reviewer", "analyst"],
  },
];
